### ISSUE TITLE
[high_level_languages] Rework slides

### ISSUE THREAD

**Issue by sudodoki** [kottans/js-slides#2]
Suggest adding vanilla es6 feautures and transpailers afterwards, less coffee, add cljs, shift focus from thorough walkthrough to overview, maybe

**Comment by sudodoki** [comment]
ES6 seems like too big & will be treated as a separate topic.

**Comment by RReverser** [comment]
I'll work on ES6 slides on my own if you wish.

**Comment by sudodoki** [comment]
Closing for now, good issue to bring up on next course.
