### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by sudodoki** [kottans/js-slides#38]
Possibly, https://creativecommons.org/licenses/by-nc-sa/2.0/ ?

**Comment by shvaikalesh** [comment]
> NonCommercial — You may not use the material for commercial purposes.

Does this forbid using slides for training inside a company?

**Comment by suchov** [comment]
Maybe https://github.com/remy/mit-license ?

**Comment by zonzujiro** [comment]
> Does this forbid using slides for training inside a company?

Forbids only if you will receive any charges for such training.

If we stay with CC, then I suggest [Attribution](https://creativecommons.org/licenses/by/4.0/) license.

If no — MIT will be ok.

**Comment by sudodoki** [comment]
@zonzujiro CC attribution sounds good.

**Comment by zonzujiro** [comment]
Please see https://github.com/Kottans/js-slides/pull/50

**Comment by sudodoki** [comment]
Closed via #50
