### ISSUE TITLE
Animated headers become unreadable on hover

### ISSUE THREAD

**Issue by nscyclone** [kottans/js-slides#43]
Headers with the `.roll` class have an animation effect on hover but sometimes text grows way too big so it doesn't fit in the header box. If I am not mistaken the class is provided by `reveal.js` itself but I suppose we should fix the styles locally. The problem persists in several presentations.
Steps to reproduce:
- Visit this [page](http://kottans.org/js-slides/js_async/#/2);
- Move your cursor over the word `PROMISES`.

Here is a [screenshot](http://i.imgur.com/ZeVfllH.png).

**Comment by sudodoki** [comment]
Yep, that's kinda known issue. For most newer slides it would originate from https://github.com/sudodoki/reveal-cleaver-theme and its styles
