### ISSUE TITLE
Deprecate all slides, move to 'archive', update index page

### ISSUE THREAD

**Issue by sudodoki** [kottans/js-slides#48]

**Comment by AMashoshyna** [comment]
see PR here: https://github.com/Kottans/js-slides/pull/49

**Comment by AMashoshyna** [comment]
@sudodoki any related changes to be made to kottans.org? If slides for other languages are outdated as well, maybe we should hide "slides" section all together.

**Comment by sudodoki** [comment]
@AMashoshyna nah, other languages don't change that fast.

**Comment by sudodoki** [comment]
Done via #49
